version: '3.7'

services:
  web:
    build:
      context: ./django-app
      dockerfile: Dockerfile.prod
    command: gunicorn -c gunicorn.conf.py 'hinzu_project.wsgi:application' --bind 0.0.0.0:8000
    volumes:
      - logs_volume:/home/app/web/logs/
      - reports_volume:/home/app/web/web_app/saved_reports/
      - static_volume:/home/app/web/staticfiles
    # expose:
    #   - 8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    restart: always
  db:
    image: postgres
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    restart: always
# dont want use nginx in prod, I guess better just 1 main nginx
  # nginx:
  #   build: ./nginx
  #   volumes:
  #     - static_volume:/home/app/web/staticfiles
  #   ports:
  #     - 1337:80
  #   depends_on:
  #     - web

volumes:
  postgres_data_prod:
  static_volume:
  reports_volume:
  logs_volume:
